# Generated by Django 4.2.7 on 2023-11-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='instances',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
