# Generated by Django 4.2.7 on 2023-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_rule_instances_delete_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('variables', models.CharField(choices=[('host', 'Host'), ('headers', 'Request headers'), ('body', 'Request body')], max_length=255)),
                ('operator', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts-with', 'Starts With'), ('ends-with', 'Ends With'), ('matches', 'Matches')], max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('block', 'Block'), ('alert', 'Alert'), ('log', 'Log')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
