# Generated by Django 4.2.7 on 2023-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_policy_delete_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='variables',
            new_name='variable',
        ),
        migrations.AddField(
            model_name='policy',
            name='selector',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
